language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
- PLONE_VERSION=4.3
matrix:
  fast_finish: true
install:
- cp development.cfg buildout.cfg
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py --setuptools-version=32.3.0 --buildout-version=2.5.3
- bin/buildout annotate
- bin/buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage -t "--layer=!Robot"
- pip install coveralls
- coveralls
notifications:
  mail: hector.velarde@gmail.com
